### PR TITLE
Changed Ui of login and SignUp

### PR DESCRIPTION
**Pull request by adarsharyan002**
opensouce

### CODE REVIEW

**Comment by adarsharyan002** [comment]
@Swarnim01 have a look

**Comment by Swarnim01** [comment]
@adarsharyan002 Looks great !.
Good practice is to have the code modular and organized, so add the images used in separate folder inside src.
Also Fix the scroll (both horizontal and vertical) that appears in Login/Signup page ( it just needs a line of code to be added in body css) :)

**Comment by Swarnim01** [comment]
@adarsharyan002 Nice :)

**Comment by Swarnim01** [comment]
@adarsharyan002 you did well on the UI part but you made the mistake of not updating your master branch with mine as there've been a lot of changes in mine repository after your fork. I too didn't thoroughly checked your PR and merged it ( which made the repo travel back to what it was before at the time of your forking and removed every changes your peers made in master branch).
So I've reverted the changes you did to get back the previous commit.
Just update your master branch ( setting upstream and pulling changes ) and then commit your changes and make a PR again to reflect your changes in master.

If you still have any doubt, feel free to contact me on any socials.

**Pull request merged**
